#!/bin/bash

# vary minute (1-9) to avoid all users' backups from kicking off @ the same time
RANGE=9; MIN=$RANDOM; let "MIN %= $RANGE"; let "MIN += 1";
at now + $MIN minutes >/dev/null 2>&1 <<-EOQ
"$HOME/bin/backup" 2>/dev/null
EOQ

