#!/bin/bash
# vary minute (1-9) to avoid all users' syncs from kicking off @ the same time
RANGE=9; MIN=$RANDOM; let "MIN %= $RANGE"; let "MIN += 1";
# if you haven't authorized etcskel-backups to write to your dropbox, this
# script will exit successfully.  We will ignore the message printed to STDERR
at 03:1$MIN >/dev/null 2>&1 <<-EOQ
"$HOME/bin/etcskel-dropbox-backups-sync" 2>/dev/null
EOQ

